version: '3.8'
services:
  mirrornode-core:
    build: .
    image: mirrornode-core:local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app:cached
